# Generated by Django 5.0.4 on 2024-04-16 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_created_at_remove_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 16, 9, 22, 42, 207392, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
