# Generated by Django 5.0.4 on 2024-04-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 12, 54, 25, 676545)),
        ),
    ]
