# Generated by Django 5.0.4 on 2024-04-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0003_alter_availabledate_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 22, 20, 23, 9, 787422)),
        ),
    ]
